# -*- coding: utf-8 -*-
"""
/***************************************************************************
 geo_calculationsDialog
                                 A QGIS plugin
 This plugin allows  to calculate the height of points and field
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-05
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Paula Domarecka Emilia Brytan
        email                : 01179125@pw.edu.pl 01179109@pw.edu.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.core import QgsPointXY
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'geo_calculations_dialog_base.ui'))


class geo_calculationsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(geo_calculationsDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.wysokoscButton.clicked.connect(self.calculate_dh)
        self.PushButton_pole.clicked.connect(self.calculate_pole)       

    def calculate_dh(self):
        selected_layer=self.mMapLayerComboBox.currentLayer()
        features=selected_layer.selectedFeatures()
        h_1=float(features[1]['wysokosc'])
        h_2=float(features[2]['wysokosc'])
        dh=h_2-h_1
        self.label_dh_result.setText(f'{dh} m')

    def calculate_pole(self):
        selected_layer = self.mMapLayerComboBox.currentLayer()
        features = selected_layer.selectedFeatures()
        punkty = []
        for o in features:
            x = float(o.geometry().asPoint().x())
            y = float(o.geometry().asPoint().y())
            p = QgsPointXY(x, y)
            punkty.append(p)

        pole = 0
        dl = len(punkty)
        for e in range(dl):
            a = (e + 1) % dl
            pole += (punkty[a].x() + punkty[e].x()) * (punkty[a].y() - punkty[e].y())
            
        pole = abs(pole) / 2 / 10000  # dzielenie po zakończeniu pętli i zamiana na hektary
        pole = round(pole, 3)
        self.label_pole.setText(f'{pole} ha')
